export const landingPackages = [
  {
    packageName: "Landing Page",
    price: "$6,500 MXN",
    description: [
      "Sitio web informativo",
      "1 año de registro de dominio",
      "1 año de servicio de hosting",
      "6 secciones de contenido",
      "Galería de 10 a 15 imágenes",
      "Animación sencilla de transición en textos",
      "Formulario de contacto",
      "Iconografía personalizada",
      "Integración de Redes Sociales",
      "Certificado de seguridad SSL",
      "Optimización del sitio web para mayor velocidad de carga",
      "1 revisión para cambios",
      "Mantenimiento cada 6 meses (10% del valor del paquete)",
    ],
  },
  {
    packageName: "Página en expansión",
    price: "$12,000 MXN",
    description: [
      "Sitio web informativo",
      "1 año de registro de dominio",
      "1 año de servicio de hosting",
      "6 secciones de contenido",
      "Galería de 15 a 30 imágenes",
      "Animación sencilla de transición en textos",
      "Formulario de contacto",
      "Iconografía personalizada",
      "Integración de Redes Sociales",
      "Botón de Whatsapp",
      "Certificado de seguridad SSL",
      "Optimización del sitio web para mayor velocidad de carga",
      "3 revisiones para cambios",
      "Mantenimiento cada 6 meses (10% del valor del paquete)",
    ],
  },
  {
    packageName: "Tienda en línea",
    price: "$18,000 MXN",
    description: [
      "Sitio web informativo",
      "1 año de registro de dominio",
      "1 año de servicio de hosting",
      "6 secciones de contenido",
      "Galería de 15 a 30 imágenes",
      "Animación sencilla de transición en textos",
      "Formulario de contacto",
      "Iconografía personalizada",
      "Integración de Redes Sociales",
      "Botón de Whatsapp",
      "Integración de Google Maps",
      "Tienda en línea con productos ilimitados",
      "Integración con pasarelas de pago",
      "Página de favoritos",
      "Panel administrativo",
      "Sugerencia de productos",
      "Certificado de seguridad SSL",
      "Optimización del sitio web para mayor velocidad de carga",
      "3 revisiones para cambios",
      "Mantenimiento cada 6 meses (10% del valor del paquete)",
      "Capacitación completa",
    ],
  },
];
