export const couponsRoutesModel = {
  systemEntry: "/sistema/cupones",
  login: "/cupones",
  register: "/cupones/registro",
  home: "/cupones/home",
  myCoupons: "/cupones/mis-cupones",
  settings: "/cupones/ajustes",
  deleteAccount: "/cupones/eliminar-cuenta",
  adminScan: "/cupones/admin/escanear",
  adminConfirmed: "/cupones/admin/confirmado",
  visitRedeem: "/visit/redeem",
  changeName: "/cupones/cambio-nombre",
  qr: "/cupones/qr",
  coupons: "/cupones/cupones",
  claimCoupon: "/cupones/:couponId",
  congrats: "/cupones/nuevo",
  visitHistory: "/cupones/visitas",
  editCouponPv: "/cuponespv/editar/:CouponId",
  editCouponApp: "/cupones/editar/:CouponId",
  pvRoot: "/cuponespv",
};

export const couponsRouteKeys = Object.freeze({
  login: "login",
  systemEntry: "systemEntry",
  register: "register",
  home: "home",
  myCoupons: "myCoupons",
  settings: "settings",
  deleteAccount: "deleteAccount",
  adminScan: "adminScan",
  adminConfirmed: "adminConfirmed",
  visitRedeem: "visitRedeem",
  changeName: "changeName",
  qr: "qr",
  coupons: "coupons",
  claimCoupon: "claimCoupon",
  congrats: "congrats",
  visitHistory: "visitHistory",
  editCouponPv: "editCouponPv",
  editCouponApp: "editCouponApp",
  pvRoot: "pvRoot",
});
