export const couponVisitsRoutesModel = {
  customer: {
    systemEntry: "/sistema/cupones",
    login: "/cupones",
    register: "/cupones/registro",
    home: "/cupones/home",
    myCoupons: "/cupones/mis-cupones",
    settings: "/cupones/ajustes",
    deleteAccount: "/cupones/eliminar-cuenta",
    adminScan: "/cupones/admin/escanear",
    adminConfirmed: "/cupones/admin/confirmado",
    visitRedeem: "/visit/redeem",
    changeName: "/cupones/cambio-nombre",
    qr: "/cupones/qr",
    coupons: "/cupones/cupones",
    claimCoupon: "/cupones/:couponId",
    congrats: "/cupones/nuevo",
    visitHistory: "/cupones/visitas",
    editCouponApp: "/cupones/editar/:CouponId",
  },
  backoffice: {
    pvRoot: "/cuponespv",
    editCouponPv: "/cuponespv/editar/:CouponId",
  },
};

export const couponVisitsRouteKeys = Object.freeze({
  systemEntry: "systemEntry",
  login: "login",
  register: "register",
  home: "home",
  myCoupons: "myCoupons",
  settings: "settings",
  deleteAccount: "deleteAccount",
  adminScan: "adminScan",
  adminConfirmed: "adminConfirmed",
  visitRedeem: "visitRedeem",
  changeName: "changeName",
  qr: "qr",
  coupons: "coupons",
  claimCoupon: "claimCoupon",
  congrats: "congrats",
  visitHistory: "visitHistory",
  editCouponPv: "editCouponPv",
  editCouponApp: "editCouponApp",
  pvRoot: "pvRoot",
});
