export const POS_V2_PATHS = {
  login: "/v2/login-punto-venta",
  sales: "/v2/MainSales",
  products: "/v2/main-products/items",
  finances: "/v2/MainFinances",
  reports: "/v2/dashboard",
  more: "/v2/more",
  morePreview: (moduleId = ":moduleId") => `/v2/more/preview/${moduleId}`,
  tableZones: "/v2/settings/table-zones",
  cashClosing: "/v2/cash-closing",
  inventory: "/v2/inventory",
  customers: "/v2/customers",
  employees: "/v2/employees",
  onlineStore: "/v2/online-store",
  health: "/v2/health",
  posRoot: "/v2/pos",
  posLoginAlias: "/v2/pos/login",
  posSalesAlias: "/v2/pos/sales",
  posProductsAlias: "/v2/pos/products",
  posFinancesAlias: "/v2/pos/finances",
  posReportsAlias: "/v2/pos/reports",
  posMoreAlias: "/v2/pos/more",
  posTablesAlias: "/v2/pos/tables",
  posHealthAlias: "/v2/pos/health",
  posInventoryAlias: "/v2/pos/inventory",
  posCashClosingAlias: "/v2/pos/cash-closing",
} as const;
