import { existsSync } from "node:fs";

const requiredPaths = [
  "src/new/core/api/HttpClient.ts",
  "src/new/core/api/FetchHttpClient.ts",
  "src/new/systems/pos/sales-management/api/PosProductApi.ts",
  "src/new/systems/pos/sales-management/interface/IProductRepository.ts",
  "src/new/systems/pos/sales-management/model/Product.ts",
  "src/new/systems/pos/sales-management/services/ProductService.ts",
  "src/new/systems/pos/sales-management/pages/SalesManagementPage.ts",
  "src/new/systems/pos/order-processing/api/PosOrderApi.ts",
  "src/new/systems/pos/order-processing/interface/IOrderRepository.ts",
  "src/new/systems/pos/order-processing/model/Order.ts",
  "src/new/systems/pos/order-processing/services/OrderService.ts",
  "src/new/systems/pos/order-processing/pages/OrderProcessingPage.ts",
  "src/new/systems/pos/reporting-insights/api/PosReportingApi.ts",
  "src/new/systems/pos/reporting-insights/interface/IReportingRepository.ts",
  "src/new/systems/pos/reporting-insights/model/SalesReport.ts",
  "src/new/systems/pos/reporting-insights/services/ReportingService.ts",
  "src/new/systems/pos/reporting-insights/pages/ReportingInsightsPage.ts",
  "src/new/systems/pos/business-settings/api/PosBusinessSettingsApi.ts",
  "src/new/systems/pos/business-settings/interface/IBusinessSettingsRepository.ts",
  "src/new/systems/pos/business-settings/model/BusinessSettings.ts",
  "src/new/systems/pos/business-settings/services/BusinessSettingsService.ts",
  "src/new/systems/pos/business-settings/pages/BusinessSettingsPage.ts",
  "src/new/systems/pos/online-order-tracking/api/PosOnlineOrderApi.ts",
  "src/new/systems/pos/online-order-tracking/interface/IOnlineOrderRepository.ts",
  "src/new/systems/pos/online-order-tracking/model/OnlineOrder.ts",
  "src/new/systems/pos/online-order-tracking/services/OnlineOrderService.ts",
  "src/new/systems/pos/online-order-tracking/pages/OnlineOrderTrackingPage.ts",
  "src/new/systems/pos/export-reporting/api/PosExportReportApi.ts",
  "src/new/systems/pos/export-reporting/interface/IExportReportRepository.ts",
  "src/new/systems/pos/export-reporting/model/ExportReport.ts",
  "src/new/systems/pos/export-reporting/services/ExportReportService.ts",
  "src/new/systems/pos/export-reporting/pages/ExportReportPage.ts",
  "src/new/systems/pos/cash-closing-management/api/PosCashClosingApi.ts",
  "src/new/systems/pos/cash-closing-management/interface/ICashClosingRepository.ts",
  "src/new/systems/pos/cash-closing-management/model/CashClosing.ts",
  "src/new/systems/pos/cash-closing-management/services/CashClosingService.ts",
  "src/new/systems/pos/cash-closing-management/pages/CashClosingPage.ts",
  "src/new/systems/pos/dashboard-analytics/api/PosDashboardApi.ts",
  "src/new/systems/pos/dashboard-analytics/interface/IDashboardRepository.ts",
  "src/new/systems/pos/dashboard-analytics/model/DashboardMetrics.ts",
  "src/new/systems/pos/dashboard-analytics/services/DashboardAnalyticsService.ts",
  "src/new/systems/pos/dashboard-analytics/pages/DashboardAnalyticsPage.ts",
  "src/new/systems/pos/finance-tracking/api/PosFinanceApi.ts",
  "src/new/systems/pos/finance-tracking/interface/IFinanceRepository.ts",
  "src/new/systems/pos/finance-tracking/model/FinanceEntry.ts",
  "src/new/systems/pos/finance-tracking/services/FinanceTrackingService.ts",
  "src/new/systems/pos/finance-tracking/pages/FinanceTrackingPage.ts",
  "src/new/systems/pos/customer-management/api/PosCustomerApi.ts",
  "src/new/systems/pos/customer-management/interface/ICustomerRepository.ts",
  "src/new/systems/pos/customer-management/model/Customer.ts",
  "src/new/systems/pos/customer-management/services/CustomerService.ts",
  "src/new/systems/pos/customer-management/pages/CustomerManagementPage.ts",
  "src/new/systems/pos/employee-management/api/PosEmployeeApi.ts",
  "src/new/systems/pos/employee-management/interface/IEmployeeRepository.ts",
  "src/new/systems/pos/employee-management/model/Employee.ts",
  "src/new/systems/pos/employee-management/services/EmployeeService.ts",
  "src/new/systems/pos/employee-management/pages/EmployeeManagementPage.ts",
  "src/new/systems/pos/inventory-management/api/PosInventoryApi.ts",
  "src/new/systems/pos/inventory-management/interface/IInventoryRepository.ts",
  "src/new/systems/pos/inventory-management/model/InventoryItem.ts",
  "src/new/systems/pos/inventory-management/services/InventoryService.ts",
  "src/new/systems/pos/inventory-management/pages/InventoryManagementPage.ts",
  "src/new/systems/pos/auth-onboarding/api/PosAuthOnboardingApi.ts",
  "src/new/systems/pos/auth-onboarding/interface/IAuthOnboardingRepository.ts",
  "src/new/systems/pos/auth-onboarding/model/AuthSession.ts",
  "src/new/systems/pos/auth-onboarding/services/AuthOnboardingService.ts",
  "src/new/systems/pos/auth-onboarding/pages/AuthOnboardingPage.ts",
  "src/new/systems/pos/table-zone-management/api/PosTableZoneApi.ts",
  "src/new/systems/pos/table-zone-management/interface/ITableZoneRepository.ts",
  "src/new/systems/pos/table-zone-management/model/TableZone.ts",
  "src/new/systems/pos/table-zone-management/services/TableZoneService.ts",
  "src/new/systems/pos/table-zone-management/pages/TableZoneManagementPage.ts",
  "src/new/systems/pos/tax-management/api/PosSalesTaxApi.ts",
  "src/new/systems/pos/tax-management/interface/ISalesTaxRepository.ts",
  "src/new/systems/pos/tax-management/model/SalesTax.ts",
  "src/new/systems/pos/tax-management/services/SalesTaxService.ts",
  "src/new/systems/pos/tax-management/pages/SalesTaxSettingsPage.ts",
  "src/new/systems/pos/features/payment-method-management/api/PosPaymentMethodApi.ts",
  "src/new/systems/pos/features/payment-method-management/interface/IPaymentMethodRepository.ts",
  "src/new/systems/pos/features/payment-method-management/model/PaymentMethod.ts",
  "src/new/systems/pos/features/payment-method-management/services/PaymentMethodService.ts",
  "src/new/systems/pos/features/payment-method-management/pages/PaymentMethodManagementPage.ts",
  "src/new/systems/catalog/product-publishing/api/CatalogApi.ts",
  "src/new/systems/catalog/product-publishing/interface/ICatalogRepository.ts",
  "src/new/systems/catalog/product-publishing/model/CatalogProduct.ts",
  "src/new/systems/catalog/product-publishing/services/CatalogService.ts",
  "src/new/systems/catalog/product-publishing/pages/CatalogPublishingPage.ts",
  "src/new/systems/loyalty/rewards-management/api/LoyaltyApi.ts",
  "src/new/systems/loyalty/rewards-management/interface/IRewardRepository.ts",
  "src/new/systems/loyalty/rewards-management/model/RewardCoupon.ts",
  "src/new/systems/loyalty/rewards-management/services/RewardService.ts",
  "src/new/systems/loyalty/rewards-management/pages/RewardsManagementPage.ts",
  "src/new/systems/index.ts",
  "src/new/systems/pos/index.ts",
  "src/new/systems/catalog/index.ts",
  "src/new/systems/loyalty/index.ts",
  "src/new/index.ts",
];

const missing = requiredPaths.filter((path) => !existsSync(path));

if (missing.length > 0) {
  console.error("Missing modern architecture files:");
  missing.forEach((path) => console.error(` - ${path}`));
  process.exit(1);
}

console.log("Modern feature-based architecture is ready.");
console.log("Systems: pos, catalog, loyalty.");
console.log("Layers per feature: interface, model, services, api, pages.");
console.log(
  "POS features: sales-management, order-processing, reporting-insights, business-settings, table-zone-management, online-order-tracking, export-reporting, cash-closing-management, dashboard-analytics, finance-tracking, customer-management, employee-management, inventory-management, auth-onboarding.",
  "POS features: sales-management, order-processing, reporting-insights, business-settings, table-zone-management, tax-management, payment-method-management, online-order-tracking, export-reporting, cash-closing-management, dashboard-analytics, finance-tracking, customer-management, employee-management, inventory-management, auth-onboarding.",
);
