import { posSettingsRouteKeys } from "../model/posSettingsRoutes";
import { buildPosSettingsFeatureRoutes } from "../service/buildPosSettingsFeatureRoutes";
import {
  PosMainSettingsPage,
  PosCatalogSettingsPage,
  PosBoxCuttingPage,
  PosCuttingByEmployeePage,
  PosPricingPage,
  PosCloseSessionPage,
  PosCustomizeAppPage,
  PosDeleteAccountPage,
  PosGeneralSettingsPage,
  PosLanguageSelectionPage,
  PosPaymentMethodsPage,
  PosSalesTaxSettingsPage,
  PosSelectMoneyPage,
  PosSettingsPPage,
  PosMainStoreOnlinePage,
  PosOrdersPage,
  PosOrderDetailsPage,
  PosUpdateStoreInfoPage,
  PosAddressStorePage,
  PosNameStorePage,
  PosPhoneStorePage,
  PosReferenceStorePage,
  PosStartedStorePage,
} from "./PosSettingsPages";

const posSettingsPageByRouteKey = {
  [posSettingsRouteKeys.main]: <PosMainSettingsPage />,
  [posSettingsRouteKeys.catalogConfig]: <PosCatalogSettingsPage />,
  [posSettingsRouteKeys.boxCutting]: <PosBoxCuttingPage />,
  [posSettingsRouteKeys.cuttingByEmployee]: <PosCuttingByEmployeePage />,
  [posSettingsRouteKeys.pricing]: <PosPricingPage />,
  [posSettingsRouteKeys.closeSession]: <PosCloseSessionPage />,
  [posSettingsRouteKeys.customizeApp]: <PosCustomizeAppPage />,
  [posSettingsRouteKeys.deleteAccount]: <PosDeleteAccountPage />,
  [posSettingsRouteKeys.generalSettings]: <PosGeneralSettingsPage />,
  [posSettingsRouteKeys.languageSelection]: <PosLanguageSelectionPage />,
  [posSettingsRouteKeys.paymentMethods]: <PosPaymentMethodsPage />,
  [posSettingsRouteKeys.salesTaxSettings]: <PosSalesTaxSettingsPage />,
  [posSettingsRouteKeys.selectMoney]: <PosSelectMoneyPage />,
  [posSettingsRouteKeys.settingsP]: <PosSettingsPPage />,
  [posSettingsRouteKeys.storeOnline]: <PosMainStoreOnlinePage />,
  [posSettingsRouteKeys.orders]: <PosOrdersPage />,
  [posSettingsRouteKeys.orderDetails]: <PosOrderDetailsPage />,
  [posSettingsRouteKeys.updateStoreInfo]: <PosUpdateStoreInfoPage />,
  [posSettingsRouteKeys.addressStore]: <PosAddressStorePage />,
  [posSettingsRouteKeys.nameStore]: <PosNameStorePage />,
  [posSettingsRouteKeys.phoneStore]: <PosPhoneStorePage />,
  [posSettingsRouteKeys.referenceStore]: <PosReferenceStorePage />,
  [posSettingsRouteKeys.startedStore]: <PosStartedStorePage />,
};

export const posSettingsFeatureRoutes = buildPosSettingsFeatureRoutes(posSettingsPageByRouteKey);
