import { MainSettings } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/MainSettings";
import { CatalogSettings } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/CatalogSettings";
import { BoxCutting } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/BoxCutting/BoxCutting";
import { CuttingByEmployee } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/BoxCutting/CuttingByEmployee";
import { AnimatedSlider } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Pricing/pricing";
import { CloseSession } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/CloseSession";
import { CustomizeApp } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/CustomizeApp";
import { DeleteAccount } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/DeleteAccount";
import { GeneralSettings } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/GeneralSettings";
import { LanguageSelection } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/LanguageSelection";
import { PaymentMethods } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/PaymentMethods";
import { SalesTaxSettings } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/SalesTaxSettings";
import { SelectMoney } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/SelectMoney";
import { SettingsP } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/Settings/SettingsP";
import { MainStoreOnline } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/MainStoreOnline";
import { OrdersScreen } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/Orders";
import { OrderDetailScreen } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/OrderDetails";
import { UpdateStoreInfo } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/UpdateStoreInfo";
import { AddressStore } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/AddressStore";
import { NameStore } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/NameStore";
import { PhoneStore } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/PhoneStore";
import { ReferenceStore } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/ReferenceStore";
import { StartedStore } from "../../../../Components/CatalogoWeb/PuntoVenta/Settings/StoreOnline/StartedStore";
import { PosAddTableView, PosEditTableView, PosExportReportsView, PosTablesView } from "../interface/PosSettingsAdvancedViews";

export const PosMainSettingsPage = () => <MainSettings />;
export const PosCatalogSettingsPage = () => <CatalogSettings />;
export const PosBoxCuttingPage = () => <BoxCutting />;
export const PosCuttingByEmployeePage = () => <CuttingByEmployee />;
export const PosPricingPage = () => <AnimatedSlider />;
export const PosCloseSessionPage = () => <CloseSession />;
export const PosCustomizeAppPage = () => <CustomizeApp />;
export const PosDeleteAccountPage = () => <DeleteAccount />;
export const PosGeneralSettingsPage = () => <GeneralSettings />;
export const PosLanguageSelectionPage = () => <LanguageSelection />;
export const PosPaymentMethodsPage = () => <PaymentMethods />;
export const PosSalesTaxSettingsPage = () => <SalesTaxSettings />;
export const PosSelectMoneyPage = () => <SelectMoney />;
export const PosSettingsPPage = () => <SettingsP />;
export const PosMainStoreOnlinePage = () => <MainStoreOnline />;
export const PosOrdersPage = () => <OrdersScreen />;
export const PosOrderDetailsPage = () => <OrderDetailScreen />;
export const PosUpdateStoreInfoPage = () => <UpdateStoreInfo />;
export const PosAddressStorePage = () => <AddressStore />;
export const PosNameStorePage = () => <NameStore />;
export const PosPhoneStorePage = () => <PhoneStore />;
export const PosReferenceStorePage = () => <ReferenceStore />;
export const PosStartedStorePage = () => <StartedStore />;
export const PosTablesPage = () => <PosTablesView />;
export const PosAddTablePage = () => <PosAddTableView />;
export const PosEditTablePage = () => <PosEditTableView />;
export const PosExportReportsPage = () => <PosExportReportsView />;
