import { MainSettings } from "../../../../legacy/pos/settings";
import { CatalogSettings } from "../../../../legacy/pos/settings";
import { BoxCutting } from "../../../../legacy/pos/settings";
import { CuttingByEmployee } from "../../../../legacy/pos/settings";
import { AnimatedSlider } from "../../../../legacy/pos/settings";
import { CloseSession } from "../../../../legacy/pos/settings";
import { CustomizeApp } from "../../../../legacy/pos/settings";
import { DeleteAccount } from "../../../../legacy/pos/settings";
import { GeneralSettings } from "../../../../legacy/pos/settings";
import { LanguageSelection } from "../../../../legacy/pos/settings";
import { PaymentMethods } from "../../../../legacy/pos/settings";
import { SalesTaxSettings } from "../../../../legacy/pos/settings";
import { SelectMoney } from "../../../../legacy/pos/settings";
import { SettingsP } from "../../../../legacy/pos/settings";
import { MainStoreOnline } from "../../../../legacy/pos/settings";
import { OrdersScreen } from "../../../../legacy/pos/settings";
import { OrderDetailScreen } from "../../../../legacy/pos/settings";
import { UpdateStoreInfo } from "../../../../legacy/pos/settings";
import { AddressStore } from "../../../../legacy/pos/settings";
import { NameStore } from "../../../../legacy/pos/settings";
import { PhoneStore } from "../../../../legacy/pos/settings";
import { ReferenceStore } from "../../../../legacy/pos/settings";
import { StartedStore } from "../../../../legacy/pos/settings";
import { PosAddTableView, PosEditTableView, PosExportReportsView, PosTablesView } from "../interface/PosSettingsAdvancedViews";

export const PosMainSettingsPage = () => <MainSettings />;
export const PosCatalogSettingsPage = () => <CatalogSettings />;
export const PosBoxCuttingPage = () => <BoxCutting />;
export const PosCuttingByEmployeePage = () => <CuttingByEmployee />;
export const PosPricingPage = () => <AnimatedSlider />;
export const PosCloseSessionPage = () => <CloseSession />;
export const PosCustomizeAppPage = () => <CustomizeApp />;
export const PosDeleteAccountPage = () => <DeleteAccount />;
export const PosGeneralSettingsPage = () => <GeneralSettings />;
export const PosLanguageSelectionPage = () => <LanguageSelection />;
export const PosPaymentMethodsPage = () => <PaymentMethods />;
export const PosSalesTaxSettingsPage = () => <SalesTaxSettings />;
export const PosSelectMoneyPage = () => <SelectMoney />;
export const PosSettingsPPage = () => <SettingsP />;
export const PosMainStoreOnlinePage = () => <MainStoreOnline />;
export const PosOrdersPage = () => <OrdersScreen />;
export const PosOrderDetailsPage = () => <OrderDetailScreen />;
export const PosUpdateStoreInfoPage = () => <UpdateStoreInfo />;
export const PosAddressStorePage = () => <AddressStore />;
export const PosNameStorePage = () => <NameStore />;
export const PosPhoneStorePage = () => <PhoneStore />;
export const PosReferenceStorePage = () => <ReferenceStore />;
export const PosStartedStorePage = () => <StartedStore />;
export const PosTablesPage = () => <PosTablesView />;
export const PosAddTablePage = () => <PosAddTableView />;
export const PosEditTablePage = () => <PosEditTableView />;
export const PosExportReportsPage = () => <PosExportReportsView />;
