export const posSettingsRoutesModel = {
  main: "/more",
  catalogConfig: "/catalog-config",
  boxCutting: "/box-cutting",
  cuttingByEmployee: "/cutting-by-employee/:employeeId",
  pricing: "/pricing",
  closeSession: "/close-session",
  customizeApp: "/customize-app",
  deleteAccount: "/delete-account",
  generalSettings: "/general-settings",
  languageSelection: "/language-selection",
  paymentMethods: "/payment-methods",
  salesTaxSettings: "/sales-tax-settings",
  selectMoney: "/select-money",
  settingsP: "/settings-p",
  storeOnline: "/main-store-online",
  orders: "/orders",
  orderDetails: "/order-details/:orderId",
  updateStoreInfo: "/update-store-info",
  addressStore: "/address-store",
  nameStore: "/name-store",
  phoneStore: "/phone-store",
  referenceStore: "/reference-store",
  startedStore: "/started-store",
  tables: "/tables",
  addTable: "/add-table",
  editTable: "/edit-table/:tableId",
  exportReports: "/export-reports",
} as const;

export const posSettingsRouteKeys = Object.freeze({
  main: "main",
  catalogConfig: "catalogConfig",
  boxCutting: "boxCutting",
  cuttingByEmployee: "cuttingByEmployee",
  pricing: "pricing",
  closeSession: "closeSession",
  customizeApp: "customizeApp",
  deleteAccount: "deleteAccount",
  generalSettings: "generalSettings",
  languageSelection: "languageSelection",
  paymentMethods: "paymentMethods",
  salesTaxSettings: "salesTaxSettings",
  selectMoney: "selectMoney",
  settingsP: "settingsP",
  storeOnline: "storeOnline",
  orders: "orders",
  orderDetails: "orderDetails",
  updateStoreInfo: "updateStoreInfo",
  addressStore: "addressStore",
  nameStore: "nameStore",
  phoneStore: "phoneStore",
  referenceStore: "referenceStore",
  startedStore: "startedStore",
  tables: "tables",
  addTable: "addTable",
  editTable: "editTable",
  exportReports: "exportReports",
} as const);

export type PosSettingsRouteKey = keyof typeof posSettingsRoutesModel;
