import { MainProducts } from "../../../../legacy/pos/products";
import { AddProduct } from "../../../../legacy/pos/products";
import { SelectCategory } from "../../../../legacy/pos/products";
import { EditProduct } from "../../../../legacy/pos/products";
import { EditCategory } from "../../../../legacy/pos/products";
import { List } from "../../../../legacy/pos/products";
import { StockProducts } from "../../../../legacy/pos/products";
import { SearchProductScreen } from "../../../../legacy/pos/products";
import { Filter } from "../../../../legacy/pos/products";
import { KeyboardStock } from "../../../../legacy/pos/products";

export const PosMainProductsPage = () => <MainProducts />;
export const PosAddProductProductsPage = () => <AddProduct />;
export const PosSelectCategoryProductPage = () => <SelectCategory />;
export const PosEditProductPage = () => <EditProduct />;
export const PosEditCategoryPage = () => <EditCategory />;
export const PosProductsListPage = () => <List />;
export const PosStockProductsPage = () => <StockProducts />;
export const PosSearchProductProductsPage = () => <SearchProductScreen />;
export const PosProductsFilterPage = () => <Filter />;
export const PosKeyboardProductPage = () => <KeyboardStock />;
